const { euler, freeCodeCampVersion } = require('./index')

test('euler 002', () => {

    /*
       Each new term in the Fibonacci sequence is generated by adding the previous two terms.
       By starting with 1 and 2, the first 10 terms will be:
       1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
       By considering the terms in the Fibonacci sequence whose values do not exceed four million,
       find the sum of the even-valued terms.
       https://projecteuler.net/problem=2
    */
    expect(freeCodeCampVersion(10)).toBe(44)
    expect(freeCodeCampVersion(18)).toBe(3382)
    expect(freeCodeCampVersion(23)).toBe(60696)
    expect(freeCodeCampVersion(43)).toBe(350704366)

    expect(euler(89)).toBe(44)
    expect(euler(4000000)).toBe(4613732)
})
